# permissions for end users to view buyers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: buyer-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: playground-k8s-crd
    app.kubernetes.io/part-of: playground-k8s-crd
    app.kubernetes.io/managed-by: kustomize
  name: buyer-viewer-role
rules:
- apiGroups:
  - transaction.mesh-shaped.top
  resources:
  - buyers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - transaction.mesh-shaped.top
  resources:
  - buyers/status
  verbs:
  - get
